export const blueTheme = {
  bgImg: '/images/bg-blue.svg',
  bgSideColor:'linear-gradient( to right, #7CA8D4, #578ABE)',
  bgColor: '#7CA8D4',
  bgIcon:'#578ABE',
  lineColor: 'rgba(82, 134, 186, 1)',
  fontColor: '#FFFFFF',
  btnColor: '#578ABE',
  btnHover: '#3F6892',
  btnDisabled: '#B7D4F1',
  btnFontColor: '#FFFFFF',
  bookMarkBg: '#7CA8D4',
  bookMarkActiveBg: '#578ABE',
  bookMarkFont: '#FFFFFF',
  selectedFont: '#578ABE',
  selectedBg: '#A1C7EE',
  selectedIcon: '#578ABE',
  noDiaryState: '#578ABE',
  goToDiaryWrite: '#578ABE',
  goToDiaryWriteHover: '#3F6892',
  todayBorderColor : '#A1C7EE',
}
export const rainbowTheme = {
  bgImg: '/images/bg-rainbow.svg',
  bgSideColor:'linear-gradient( to right, #FEE6EB, #FDBDCA)',
  bgColor: '#FEE6EB',
  bgIcon:'#EB8888',
  lineColor: 'rgba(253, 189, 202, 1)',
  fontColor: '#373737',
  btnColor: '#EB8888',
  btnHover: '#FF839C',
  btnDisabled: '#FDAEBE',
  btnFontColor: '#FFFFFF',
  bookMarkBg: '#FFD2DC',
  bookMarkActiveBg: '#EB8888',
  bookMarkFont: '#373737',
  selectedFont: '#EB8888',
  selectedBg: '#FFD2DC',
  selectedIcon: '#EB8888',
  noDiaryState: '#EB8888',
  goToDiaryWrite: '#EB8888',
  goToDiaryWriteHover: '#FF839C',
  todayBorderColor : '#FDAEBE',
}
export const originTheme = {
  bgImg:'/images/background.PNG',
  bgSideColor:'linear-gradient( to right, #FAECC8, #F0D15D)',
  bgColor: '#FAECC8',
  bgIcon:'#EAB839',
  lineColor: 'rgba(240, 209, 93, 1)',
  fontColor: '#373737',
  btnColor:'#EAB839',
  btnHover: '#FAC130',
  btnDisabled: '#FFE39A',
  btnFontColor: '#FFFFFF',
  bookMarkBg: '#F2DF9A',
  bookMarkActiveBg: '#F0D15D',
  bookMarkFont: '#373737',
  selectedFont: '#EAB839',
  selectedBg: '#F2DF9A',
  selectedIcon: '#EAB839',
  noDiaryState: '#EAB839',
  goToDiaryWrite: '#EAB839',
  goToDiaryWriteHover: '#FAC130',
  todayBorderColor : '#F2DF9A',
}

export const theme = {
  blueTheme,
  rainbowTheme,
  originTheme
}

export default theme;